#!/bin/sh
set -e

lb config noauto \
  --distribution trixie \
  --architectures amd64 \
  --archive-areas "main contrib non-free non-free-firmware" \
  --linux-packages "linux-image" \
  --binary-images iso-hybrid \
  --iso-application "Stephan-OS" \
  --iso-volume "Stephan-OS" \
  --iso-publisher "Stephan-Lefty" \
  --memtest none \
  --win32-loader false \
  --firmware-chroot false \
  --firmware-binary false \
  "${@}"
